apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-collector
  namespace: keti-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-collector
  namespace: keti-system
subjects:
- kind: ServiceAccount
  name: metric-collector
  namespace: keti-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: metric-collector
  namespace: keti-system
  labels:
    name: metric-collector-gpu
spec:
  type: NodePort
  ports:
  - port: 50052
    name: grpc
    targetPort: 50052
    nodePort: 32551
    protocol: TCP
  - port: 9395
    name: rest
    targetPort: 9395
    nodePort: 32395
    protocol: TCP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metric-collector
  namespace: keti-system
spec:
  selector:
    matchLabels:
      name: metric-collector-gpu
  template:
    metadata:
      labels:
        name: metric-collector-gpu
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ketidevit2/exascale.metric-collector:latest
        imagePullPolicy: Always
        name: metric-collector
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 9394
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: keti-user
      nodeSelector:
        gpu: "on"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metric-collector
      serviceAccountName: metric-collector
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate