apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-mapper
  namespace: keti-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-mapper
  namespace: keti-system
subjects:
- kind: ServiceAccount
  name: pod-mapper
  namespace: keti-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: pod-mapper
  namespace: keti-system
  labels:
    name: pod-mapper
spec:
  type: NodePort
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 32551
    protocol: TCP
  - port: 9394
    targetPort: 9394
    nodePort: 32994
    protocol: TCP
  selector:
    name: pod-mapper
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keti-pod-mapper
  namespace: keti-system
spec:
  selector:
    matchLabels:
      name: keti-pod-mapper
  template:
    metadata:
      labels:
        name: keti-pod-mapper
    spec:
      serviceAccountName: pod-mapper
      imagePullSecrets:
      - name: harbor-user
      restartPolicy: Always
      containers:
      - name: pod-mapper
        image: ketidevit.repo/exascale/pod-mapper:latest
        volumeMounts:
        - name: containers
          mountPath: /var/lib/docker/containers
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers


