apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-collector
  namespace: keti-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-collector
  namespace: keti-system
subjects:
- kind: ServiceAccount
  name: metric-collector
  namespace: keti-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: metric-collector
  namespace: keti-system
  labels:
    name: metric-collector
spec:
  type: NodePort
  ports:
  - port: 50052
    name: grpc
    targetPort: 50052
    nodePort: 32551
    protocol: TCP
  - port: 9395
    name: rest
    targetPort: 9395
    nodePort: 32395
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: keti-metric-collector-gpu-node1
  namespace: keti-system
  labels:
    name: keti-metric-collector
spec:
  nodeName: gpu-node1
  serviceAccountName: metric-collector
  imagePullSecrets:
  - name: keti-user
  restartPolicy: Always
  containers:
  - name: metric-collector
    image: ketidevit2/exascale.metric-collector:latest
    ports:
    - containerPort: 50052
    - containerPort: 9395
    volumeMounts:
    - name: containers
      mountPath: /var/lib/docker/containers
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        nvidia.com/gpu: 1
  volumes:
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
---
apiVersion: v1
kind: Pod
metadata:
  name: keti-metric-collector-gpu-node2
  namespace: keti-system
  labels:
    name: keti-metric-collector
spec:
  nodeName: gpu-node2
  serviceAccountName: metric-collector
  imagePullSecrets:
  - name: harbor-user
  restartPolicy: Always
  containers:
  - name: metric-collector
    image: ketidevit2/exascale.metric-collector:latest
    ports:
    - containerPort: 50052
    - containerPort: 9395
    volumeMounts:
    - name: containers
      mountPath: /var/lib/docker/containers
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        nvidia.com/gpu: 1
  volumes:
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
---
apiVersion: v1
kind: Pod
metadata:
  name: keti-metric-collector-cpu-node1
  namespace: keti-system
  labels:
    name: keti-metric-collector
spec:
  nodeName: cpu-node1
  serviceAccountName: metric-collector
  imagePullSecrets:
  - name: harbor-user
  restartPolicy: Always
  containers:
  - name: metric-collector
    image: ketidevit2/exascale.metric-collector:latest
    ports:
    - containerPort: 50052
    - containerPort: 9395
    volumeMounts:
    - name: containers
      mountPath: /var/lib/docker/containers
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  volumes:
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
---
apiVersion: v1
kind: Pod
metadata:
  name: keti-metric-collector-c1-master
  namespace: keti-system
  labels:
    name: keti-metric-collector
spec:
  nodeName: c1-master
  serviceAccountName: metric-collector
  imagePullSecrets:
  - name: harbor-user
  restartPolicy: Always
  containers:
  - name: metric-collector
    image: ketidevit2/exascale.metric-collector:latest
    ports:
    - containerPort: 50052
    - containerPort: 9395
    volumeMounts:
    - name: containers
      mountPath: /var/lib/docker/containers
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  volumes:
  - name: containers
    hostPath:
      path: /var/lib/docker/containers


